# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/xilinx_prj/xilinx_FrameBuffer/xtp_hdmi_ex/hw/v_hdmi_tx_ss/v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_vid_phy_controller_0/zcu106_hdmi_platform_vid_phy_controller_0.xci
# IP: The module: 'zcu106_hdmi_platform_vid_phy_controller_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: d:/xilinx_prj/xilinx_FrameBuffer/xtp_hdmi_ex/hw/v_hdmi_tx_ss/v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_vid_phy_controller_0/ip_0/zcu106_hdmi_platform_vid_phy_controller_0_gtwrapper.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zcu106_hdmi_platform_vid_phy_controller_0_gtwrapper || ORIG_REF_NAME==zcu106_hdmi_platform_vid_phy_controller_0_gtwrapper} -quiet] -quiet

# XDC: d:/xilinx_prj/xilinx_FrameBuffer/xtp_hdmi_ex/hw/v_hdmi_tx_ss/v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_vid_phy_controller_0/ip_0/synth/zcu106_hdmi_platform_vid_phy_controller_0_gtwrapper_ooc.xdc

# XDC: d:/xilinx_prj/xilinx_FrameBuffer/xtp_hdmi_ex/hw/v_hdmi_tx_ss/v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_vid_phy_controller_0/ip_0/synth/zcu106_hdmi_platform_vid_phy_controller_0_gtwrapper.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==zcu106_hdmi_platform_vid_phy_controller_0_gtwrapper || ORIG_REF_NAME==zcu106_hdmi_platform_vid_phy_controller_0_gtwrapper} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/xilinx_prj/xilinx_FrameBuffer/xtp_hdmi_ex/hw/v_hdmi_tx_ss/v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_vid_phy_controller_0/vid_phy_controller_xdc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zcu106_hdmi_platform_vid_phy_controller_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/xilinx_prj/xilinx_FrameBuffer/xtp_hdmi_ex/hw/v_hdmi_tx_ss/v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_vid_phy_controller_0/zcu106_hdmi_platform_vid_phy_controller_0_ooc_fixed.xdc
# XDC: The top module name and the constraint reference have the same name: 'zcu106_hdmi_platform_vid_phy_controller_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/xilinx_prj/xilinx_FrameBuffer/xtp_hdmi_ex/hw/v_hdmi_tx_ss/v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_vid_phy_controller_0/zcu106_hdmi_platform_vid_phy_controller_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'zcu106_hdmi_platform_vid_phy_controller_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/xilinx_prj/xilinx_FrameBuffer/xtp_hdmi_ex/hw/v_hdmi_tx_ss/v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_vid_phy_controller_0/zcu106_hdmi_platform_vid_phy_controller_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zcu106_hdmi_platform_vid_phy_controller_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: d:/xilinx_prj/xilinx_FrameBuffer/xtp_hdmi_ex/hw/v_hdmi_tx_ss/v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_vid_phy_controller_0/zcu106_hdmi_platform_vid_phy_controller_0.xci
# IP: The module: 'zcu106_hdmi_platform_vid_phy_controller_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: d:/xilinx_prj/xilinx_FrameBuffer/xtp_hdmi_ex/hw/v_hdmi_tx_ss/v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_vid_phy_controller_0/ip_0/zcu106_hdmi_platform_vid_phy_controller_0_gtwrapper.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zcu106_hdmi_platform_vid_phy_controller_0_gtwrapper || ORIG_REF_NAME==zcu106_hdmi_platform_vid_phy_controller_0_gtwrapper} -quiet] -quiet

# XDC: d:/xilinx_prj/xilinx_FrameBuffer/xtp_hdmi_ex/hw/v_hdmi_tx_ss/v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_vid_phy_controller_0/ip_0/synth/zcu106_hdmi_platform_vid_phy_controller_0_gtwrapper_ooc.xdc

# XDC: d:/xilinx_prj/xilinx_FrameBuffer/xtp_hdmi_ex/hw/v_hdmi_tx_ss/v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_vid_phy_controller_0/ip_0/synth/zcu106_hdmi_platform_vid_phy_controller_0_gtwrapper.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==zcu106_hdmi_platform_vid_phy_controller_0_gtwrapper || ORIG_REF_NAME==zcu106_hdmi_platform_vid_phy_controller_0_gtwrapper} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/xilinx_prj/xilinx_FrameBuffer/xtp_hdmi_ex/hw/v_hdmi_tx_ss/v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_vid_phy_controller_0/vid_phy_controller_xdc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zcu106_hdmi_platform_vid_phy_controller_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/xilinx_prj/xilinx_FrameBuffer/xtp_hdmi_ex/hw/v_hdmi_tx_ss/v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_vid_phy_controller_0/zcu106_hdmi_platform_vid_phy_controller_0_ooc_fixed.xdc
# XDC: The top module name and the constraint reference have the same name: 'zcu106_hdmi_platform_vid_phy_controller_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/xilinx_prj/xilinx_FrameBuffer/xtp_hdmi_ex/hw/v_hdmi_tx_ss/v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_vid_phy_controller_0/zcu106_hdmi_platform_vid_phy_controller_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'zcu106_hdmi_platform_vid_phy_controller_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/xilinx_prj/xilinx_FrameBuffer/xtp_hdmi_ex/hw/v_hdmi_tx_ss/v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_vid_phy_controller_0/zcu106_hdmi_platform_vid_phy_controller_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zcu106_hdmi_platform_vid_phy_controller_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
