# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/xilinx_prj/xilinx_FrameBuffer/xtp_hdmi_ex/hw/v_hdmi_tx_ss/v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_s00_regslice_1/zcu106_hdmi_platform_s00_regslice_1.xci
# IP: The module: 'zcu106_hdmi_platform_s00_regslice_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/xilinx_prj/xilinx_FrameBuffer/xtp_hdmi_ex/hw/v_hdmi_tx_ss/v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_s00_regslice_1/zcu106_hdmi_platform_s00_regslice_1_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'zcu106_hdmi_platform_s00_regslice_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/xilinx_prj/xilinx_FrameBuffer/xtp_hdmi_ex/hw/v_hdmi_tx_ss/v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_s00_regslice_1/zcu106_hdmi_platform_s00_regslice_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zcu106_hdmi_platform_s00_regslice_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: d:/xilinx_prj/xilinx_FrameBuffer/xtp_hdmi_ex/hw/v_hdmi_tx_ss/v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_s00_regslice_1/zcu106_hdmi_platform_s00_regslice_1.xci
# IP: The module: 'zcu106_hdmi_platform_s00_regslice_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/xilinx_prj/xilinx_FrameBuffer/xtp_hdmi_ex/hw/v_hdmi_tx_ss/v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_s00_regslice_1/zcu106_hdmi_platform_s00_regslice_1_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'zcu106_hdmi_platform_s00_regslice_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/xilinx_prj/xilinx_FrameBuffer/xtp_hdmi_ex/hw/v_hdmi_tx_ss/v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_s00_regslice_1/zcu106_hdmi_platform_s00_regslice_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zcu106_hdmi_platform_s00_regslice_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
