#!/bin/bash -f
#*********************************************************************************************************
# Vivado (TM) v2018.1 (64-bit)
#
# Filename    : zcu106_hdmi_platform.sh
# Simulator   : Synopsys Verilog Compiler Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do/prj' file, execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Sat Apr 20 16:30:51 +0800 2024
# SW Build 2188600 on Wed Apr  4 18:40:38 MDT 2018
#
# Copyright 1986-2018 Xilinx, Inc. All Rights Reserved. 
#
# usage: zcu106_hdmi_platform.sh [-help]
# usage: zcu106_hdmi_platform.sh [-lib_map_path]
# usage: zcu106_hdmi_platform.sh [-noclean_files]
# usage: zcu106_hdmi_platform.sh [-reset_run]
#
# Prerequisite:- To compile and run simulation, you must compile the Xilinx simulation libraries using the
# 'compile_simlib' TCL command. For more information about this command, run 'compile_simlib -help' in the
# Vivado Tcl Shell. Once the libraries have been compiled successfully, specify the -lib_map_path switch
# that points to these libraries and rerun export_simulation. For more information about this switch please
# type 'export_simulation -help' in the Tcl shell.
#
# You can also point to the simulation libraries by either replacing the <SPECIFY_COMPILED_LIB_PATH> in this
# script with the compiled library directory path or specify this path with the '-lib_map_path' switch when
# executing this script. Please type 'zcu106_hdmi_platform.sh -help' for more information.
#
# Additional references - 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#*********************************************************************************************************

# Directory path for design sources and include directories (if any) wrt this path
ref_dir="."

# Override directory with 'export_sim_ref_dir' env path value if set in the shell
if [[ (! -z "$export_sim_ref_dir") && ($export_sim_ref_dir != "") ]]; then
  ref_dir="$export_sim_ref_dir"
fi

# Command line options
vlogan_opts="-full64"
vhdlan_opts="-full64"
vcs_elab_opts="-full64 -debug_pp -t ps -licqueue -l elaborate.log"
vcs_sim_opts="-ucli -licqueue -l simulate.log"

# Design libraries
design_libs=(xilinx_vip xil_defaultlib xpm xlconstant_v1_1_4 xlconcat_v2_1_1 lib_cdc_v1_0_2 proc_sys_reset_v5_0_12 gtwizard_ultrascale_v1_7_3 vid_phy_controller_v2_2_0 generic_baseblocks_v2_1_0 fifo_generator_v13_2_2 axi_data_fifo_v2_1_15 xlslice_v1_0_1 v_frmbuf_wr_v2_0_2 axi_lite_ipif_v3_0_4 v_tc_v6_1_12 v_tpg_v7_0_10 v_vid_in_axi4s_v4_0_8 lib_pkg_v1_0_2 interrupt_control_v3_1_4 axi_iic_v2_0_19 axi_infrastructure_v1_1_0 smartconnect_v1_0 axi_protocol_checker_v2_0_2 axi_vip_v1_1_2 zynq_ultra_ps_e_vip_v1_0_2 axi_register_slice_v2_1_16 axi_crossbar_v2_1_17 v_frmbuf_rd_v2_0_2 v_hdmi_tx_v3_0_0 v_axi4s_vid_out_v4_0_9 util_vector_logic_v2_0_1 v_mix_v3_0_0 v_hdmi_rx_v3_0_0 v_vscaler_v1_0_10 v_hscaler_v1_0_10 axis_infrastructure_v1_1_0 axis_register_slice_v1_1_16 axis_subset_converter_v1_1_16 axi_gpio_v2_0_18 axis_data_fifo_v1_1_17 axi_clock_converter_v2_1_15 axi_protocol_converter_v2_1_16 blk_mem_gen_v8_4_1 axi_dwidth_converter_v2_1_16)

# Simulation root library directory
sim_lib_dir="vcs_lib"

# Script info
echo -e "zcu106_hdmi_platform.sh - Script generated by export_simulation (Vivado v2018.1 (64-bit)-id)\n"

# Main steps
run()
{
  check_args $# $1
  setup $1 $2
  compile
  elaborate
  simulate
}

# RUN_STEP: <compile>
compile()
{
  # Compile design files
  vlogan -work xilinx_vip $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/4903" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/472d/hdl/src/verilog" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/ad7b/hdl" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/0ab1/hdl" +incdir+"D:/tools/xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "D:/tools/xilinx/Vivado/2018.1/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
    "D:/tools/xilinx/Vivado/2018.1/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
    "D:/tools/xilinx/Vivado/2018.1/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
    "D:/tools/xilinx/Vivado/2018.1/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
    "D:/tools/xilinx/Vivado/2018.1/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
    "D:/tools/xilinx/Vivado/2018.1/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
    "D:/tools/xilinx/Vivado/2018.1/data/xilinx_vip/hdl/axi_vip_if.sv" \
    "D:/tools/xilinx/Vivado/2018.1/data/xilinx_vip/hdl/clk_vip_if.sv" \
    "D:/tools/xilinx/Vivado/2018.1/data/xilinx_vip/hdl/rst_vip_if.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/4903" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/472d/hdl/src/verilog" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/ad7b/hdl" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/0ab1/hdl" +incdir+"D:/tools/xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "D:/tools/xilinx/Vivado/2018.1/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
    "D:/tools/xilinx/Vivado/2018.1/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
    "D:/tools/xilinx/Vivado/2018.1/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xpm $vhdlan_opts \
    "D:/tools/xilinx/Vivado/2018.1/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/4903" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/472d/hdl/src/verilog" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/ad7b/hdl" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/0ab1/hdl" +incdir+"D:/tools/xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_clk_wiz_1_0/zcu106_hdmi_platform_clk_wiz_1_0_clk_wiz.v" \
    "$ref_dir/../../../bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_clk_wiz_1_0/zcu106_hdmi_platform_clk_wiz_1_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xlconstant_v1_1_4 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/4903" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/472d/hdl/src/verilog" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/ad7b/hdl" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/0ab1/hdl" +incdir+"D:/tools/xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/2fc9/hdl/xlconstant_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/4903" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/472d/hdl/src/verilog" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/ad7b/hdl" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/0ab1/hdl" +incdir+"D:/tools/xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_gnd_const_0/sim/zcu106_hdmi_platform_gnd_const_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xlconcat_v2_1_1 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/4903" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/472d/hdl/src/verilog" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/ad7b/hdl" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/0ab1/hdl" +incdir+"D:/tools/xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/2f66/hdl/xlconcat_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/4903" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/472d/hdl/src/verilog" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/ad7b/hdl" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/0ab1/hdl" +incdir+"D:/tools/xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_interrupts_0/sim/zcu106_hdmi_platform_interrupts_0.v" \
    "$ref_dir/../../../bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_interrupts1_0/sim/zcu106_hdmi_platform_interrupts1_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_cdc_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work proc_sys_reset_v5_0_12 $vhdlan_opts \
    "$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/f86a/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_proc_sys_reset_1_0/sim/zcu106_hdmi_platform_proc_sys_reset_1_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/4903" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/472d/hdl/src/verilog" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/ad7b/hdl" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/0ab1/hdl" +incdir+"D:/tools/xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/feef/sources_1/new/hdmi_hb.v" \
    "$ref_dir/../../../bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_rx_hdmi_hb_0_0/sim/zcu106_hdmi_platform_rx_hdmi_hb_0_0.v" \
    "$ref_dir/../../../bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_tx_hdmi_hb_0_0/sim/zcu106_hdmi_platform_tx_hdmi_hb_0_0.v" \
    "$ref_dir/../../../bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_vcc_const_0/sim/zcu106_hdmi_platform_vcc_const_0.v" \
    "$ref_dir/d:/xilinx_prj/xilinx_FrameBuffer/xtp_hdmi_ex/hw/v_hdmi_tx_ss/v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_vcu_0_0/zcu106_hdmi_platform_vcu_0_0_sim_netlist.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work gtwizard_ultrascale_v1_7_3 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/4903" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/472d/hdl/src/verilog" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/ad7b/hdl" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/0ab1/hdl" +incdir+"D:/tools/xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/3c4f/hdl/gtwizard_ultrascale_v1_7_bit_sync.v" \
    "$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/3c4f/hdl/gtwizard_ultrascale_v1_7_gte4_drp_arb.v" \
    "$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/3c4f/hdl/gtwizard_ultrascale_v1_7_gthe4_delay_powergood.v" \
    "$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/3c4f/hdl/gtwizard_ultrascale_v1_7_gtye4_delay_powergood.v" \
    "$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/3c4f/hdl/gtwizard_ultrascale_v1_7_gthe3_cpll_cal.v" \
    "$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/3c4f/hdl/gtwizard_ultrascale_v1_7_gthe3_cal_freqcnt.v" \
    "$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/3c4f/hdl/gtwizard_ultrascale_v1_7_gthe4_cpll_cal.v" \
    "$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/3c4f/hdl/gtwizard_ultrascale_v1_7_gthe4_cpll_cal_rx.v" \
    "$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/3c4f/hdl/gtwizard_ultrascale_v1_7_gthe4_cpll_cal_tx.v" \
    "$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/3c4f/hdl/gtwizard_ultrascale_v1_7_gthe4_cal_freqcnt.v" \
    "$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/3c4f/hdl/gtwizard_ultrascale_v1_7_gtye4_cpll_cal.v" \
    "$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/3c4f/hdl/gtwizard_ultrascale_v1_7_gtye4_cpll_cal_rx.v" \
    "$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/3c4f/hdl/gtwizard_ultrascale_v1_7_gtye4_cpll_cal_tx.v" \
    "$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/3c4f/hdl/gtwizard_ultrascale_v1_7_gtye4_cal_freqcnt.v" \
    "$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/3c4f/hdl/gtwizard_ultrascale_v1_7_gtwiz_buffbypass_rx.v" \
    "$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/3c4f/hdl/gtwizard_ultrascale_v1_7_gtwiz_buffbypass_tx.v" \
    "$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/3c4f/hdl/gtwizard_ultrascale_v1_7_gtwiz_reset.v" \
    "$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/3c4f/hdl/gtwizard_ultrascale_v1_7_gtwiz_userclk_rx.v" \
    "$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/3c4f/hdl/gtwizard_ultrascale_v1_7_gtwiz_userclk_tx.v" \
    "$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/3c4f/hdl/gtwizard_ultrascale_v1_7_gtwiz_userdata_rx.v" \
    "$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/3c4f/hdl/gtwizard_ultrascale_v1_7_gtwiz_userdata_tx.v" \
    "$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/3c4f/hdl/gtwizard_ultrascale_v1_7_reset_sync.v" \
    "$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/3c4f/hdl/gtwizard_ultrascale_v1_7_reset_inv_sync.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/4903" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/472d/hdl/src/verilog" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/ad7b/hdl" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/0ab1/hdl" +incdir+"D:/tools/xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_vid_phy_controller_0/ip_0/sim/gtwizard_ultrascale_v1_7_gthe4_channel.v" \
    "$ref_dir/../../../bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_vid_phy_controller_0/ip_0/sim/zcu106_hdmi_platform_vid_phy_controller_0_gtwrapper_gthe4_channel_wrapper.v" \
    "$ref_dir/../../../bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_vid_phy_controller_0/ip_0/sim/zcu106_hdmi_platform_vid_phy_controller_0_gtwrapper_gtwizard_gthe4.v" \
    "$ref_dir/../../../bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_vid_phy_controller_0/ip_0/sim/zcu106_hdmi_platform_vid_phy_controller_0_gtwrapper_gtwizard_top.v" \
    "$ref_dir/../../../bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_vid_phy_controller_0/ip_0/sim/zcu106_hdmi_platform_vid_phy_controller_0_gtwrapper.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work vid_phy_controller_v2_2_0 $vhdlan_opts \
    "$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/472d/hdl/src/vhd/nidru_20_v_7.vhd" \
    "$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/472d/hdl/src/vhd/bs_flex_v_2.vhd" \
    "$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/472d/hdl/src/vhd/nidru_20_wrapper.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work vid_phy_controller_v2_2_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/4903" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/472d/hdl/src/verilog" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/ad7b/hdl" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/0ab1/hdl" +incdir+"D:/tools/xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/472d/hdl/src/verilog/vid_phy_controller_v2_2_lib.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work vid_phy_controller_v2_2_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/4903" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/472d/hdl/src/verilog" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/ad7b/hdl" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/0ab1/hdl" +incdir+"D:/tools/xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/472d/hdl/src/verilog/vid_phy_controller_v2_2_sync_block.v" \
    "$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/472d/hdl/src/verilog/vid_phy_controller_v2_2_sync_pulse.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/4903" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/472d/hdl/src/verilog" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/ad7b/hdl" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/0ab1/hdl" +incdir+"D:/tools/xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_vid_phy_controller_0/hdl/src/verilog/zcu106_hdmi_platform_vid_phy_controller_0_gtxe2_hdmi_txaln.v" \
    "$ref_dir/../../../bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_vid_phy_controller_0/hdl/src/verilog/zcu106_hdmi_platform_vid_phy_controller_0_gtxe2_hdmi_xcvr.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work vid_phy_controller_v2_2_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/4903" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/472d/hdl/src/verilog" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/ad7b/hdl" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/0ab1/hdl" +incdir+"D:/tools/xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/472d/hdl/src/verilog/vid_phy_controller_v2_2_cpll_railing.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work vid_phy_controller_v2_2_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/4903" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/472d/hdl/src/verilog" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/ad7b/hdl" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/0ab1/hdl" +incdir+"D:/tools/xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/472d/hdl/src/verilog/vid_phy_controller_v2_2_datawidth_conv.sv" \
    "$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/472d/hdl/src/verilog/vid_phy_controller_v2_2_gt_tx_tmdsclk_patgen.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/4903" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/472d/hdl/src/verilog" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/ad7b/hdl" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/0ab1/hdl" +incdir+"D:/tools/xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_vid_phy_controller_0/hdl/src/verilog/zcu106_hdmi_platform_vid_phy_controller_0_clkdet.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work vid_phy_controller_v2_2_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/4903" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/472d/hdl/src/verilog" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/ad7b/hdl" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/0ab1/hdl" +incdir+"D:/tools/xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/472d/hdl/src/verilog/vid_phy_controller_v2_2_dru.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work vid_phy_controller_v2_2_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/4903" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/472d/hdl/src/verilog" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/ad7b/hdl" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/0ab1/hdl" +incdir+"D:/tools/xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/472d/hdl/src/verilog/vid_phy_controller_v2_2_axi4lite.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/4903" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/472d/hdl/src/verilog" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/ad7b/hdl" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/0ab1/hdl" +incdir+"D:/tools/xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_vid_phy_controller_0/hdl/src/verilog/zcu106_hdmi_platform_vid_phy_controller_0_gt_usrclk_source.v" \
    "$ref_dir/../../../bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_vid_phy_controller_0/hdl/src/verilog/zcu106_hdmi_platform_vid_phy_controller_0_gt_usrclk_source_8series.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work vid_phy_controller_v2_2_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/4903" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/472d/hdl/src/verilog" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/ad7b/hdl" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/0ab1/hdl" +incdir+"D:/tools/xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/472d/hdl/src/verilog/vid_phy_controller_v2_2_drp_control.v" \
    "$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/472d/hdl/src/verilog/vid_phy_controller_v2_2_drp_control_8series.v" \
    "$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/472d/hdl/src/verilog/vid_phy_controller_v2_2_drp_control_hdmi.v" \
    "$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/472d/hdl/src/verilog/vid_phy_controller_v2_2_interrupts.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/4903" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/472d/hdl/src/verilog" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/ad7b/hdl" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/0ab1/hdl" +incdir+"D:/tools/xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_vid_phy_controller_0/hdl/src/verilog/zcu106_hdmi_platform_vid_phy_controller_0_CLOCK_MODULE.v" \
    "$ref_dir/../../../bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_vid_phy_controller_0/hdl/src/verilog/zcu106_hdmi_platform_vid_phy_controller_0_CLOCK_MODULE_8series.v" \
    "$ref_dir/../../../bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_vid_phy_controller_0/hdl/src/verilog/zcu106_hdmi_platform_vid_phy_controller_0_plle2_drp.v" \
    "$ref_dir/../../../bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_vid_phy_controller_0/hdl/src/verilog/zcu106_hdmi_platform_vid_phy_controller_0_mmcme2_drp.v" \
    "$ref_dir/../../../bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_vid_phy_controller_0/hdl/src/verilog/zcu106_hdmi_platform_vid_phy_controller_0_mmcme3_drp.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work vid_phy_controller_v2_2_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/4903" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/472d/hdl/src/verilog" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/ad7b/hdl" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/0ab1/hdl" +incdir+"D:/tools/xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/472d/hdl/src/verilog/vid_phy_controller_v2_2_gtp_common.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/4903" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/472d/hdl/src/verilog" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/ad7b/hdl" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/0ab1/hdl" +incdir+"D:/tools/xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_vid_phy_controller_0/hdl/src/verilog/zcu106_hdmi_platform_vid_phy_controller_0_gthe4_common.v" \
    "$ref_dir/../../../bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_vid_phy_controller_0/hdl/src/verilog/zcu106_hdmi_platform_vid_phy_controller_0_gtwrapper_gthe4_common_wrapper.v" \
    "$ref_dir/../../../bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_vid_phy_controller_0/synth/vid_phy_controller_v2_2_0_defs.v" \
    "$ref_dir/../../../bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_vid_phy_controller_0/synth/zcu106_hdmi_platform_vid_phy_controller_0_top.v" \
    "$ref_dir/../../../bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_vid_phy_controller_0/sim/zcu106_hdmi_platform_vid_phy_controller_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work generic_baseblocks_v2_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/4903" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/472d/hdl/src/verilog" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/ad7b/hdl" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/0ab1/hdl" +incdir+"D:/tools/xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/b752/hdl/generic_baseblocks_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work fifo_generator_v13_2_2 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/4903" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/472d/hdl/src/verilog" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/ad7b/hdl" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/0ab1/hdl" +incdir+"D:/tools/xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/7aff/simulation/fifo_generator_vlog_beh.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work fifo_generator_v13_2_2 $vhdlan_opts \
    "$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/7aff/hdl/fifo_generator_v13_2_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_2_2 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/4903" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/472d/hdl/src/verilog" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/ad7b/hdl" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/0ab1/hdl" +incdir+"D:/tools/xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/7aff/hdl/fifo_generator_v13_2_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_data_fifo_v2_1_15 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/4903" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/472d/hdl/src/verilog" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/ad7b/hdl" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/0ab1/hdl" +incdir+"D:/tools/xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/d114/hdl/axi_data_fifo_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/4903" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/472d/hdl/src/verilog" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/ad7b/hdl" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/0ab1/hdl" +incdir+"D:/tools/xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_axi_data_fifo_0_1/sim/zcu106_hdmi_platform_axi_data_fifo_0_1.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xlslice_v1_0_1 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/4903" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/472d/hdl/src/verilog" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/ad7b/hdl" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/0ab1/hdl" +incdir+"D:/tools/xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/f3db/hdl/xlslice_v1_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/4903" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/472d/hdl/src/verilog" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/ad7b/hdl" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/0ab1/hdl" +incdir+"D:/tools/xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_tpg_0_VTP_reset_0/sim/zcu106_hdmi_platform_tpg_0_VTP_reset_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work v_frmbuf_wr_v2_0_2 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/4903" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/472d/hdl/src/verilog" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/ad7b/hdl" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/0ab1/hdl" +incdir+"D:/tools/xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_v_frmbuf_wr_0_1/hdl/v_frmbuf_wr_v2_0_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/4903" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/472d/hdl/src/verilog" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/ad7b/hdl" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/0ab1/hdl" +incdir+"D:/tools/xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_v_frmbuf_wr_0_1/sim/zcu106_hdmi_platform_v_frmbuf_wr_0_1.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work axi_lite_ipif_v3_0_4 $vhdlan_opts \
    "$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/cced/hdl/axi_lite_ipif_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work v_tc_v6_1_12 $vhdlan_opts \
    "$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/6694/hdl/v_tc_v6_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_v_tc_1_0/sim/zcu106_hdmi_platform_v_tc_1_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work v_tpg_v7_0_10 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/4903" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/472d/hdl/src/verilog" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/ad7b/hdl" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/0ab1/hdl" +incdir+"D:/tools/xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_v_tpg_1_0/hdl/v_tpg_v7_0_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/4903" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/472d/hdl/src/verilog" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/ad7b/hdl" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/0ab1/hdl" +incdir+"D:/tools/xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_v_tpg_1_0/sim/zcu106_hdmi_platform_v_tpg_1_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work v_vid_in_axi4s_v4_0_8 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/4903" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/472d/hdl/src/verilog" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/ad7b/hdl" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/0ab1/hdl" +incdir+"D:/tools/xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/d987/hdl/v_vid_in_axi4s_v4_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/4903" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/472d/hdl/src/verilog" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/ad7b/hdl" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/0ab1/hdl" +incdir+"D:/tools/xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_v_vid_in_axi4s_0_0/sim/zcu106_hdmi_platform_v_vid_in_axi4s_0_0.v" \
    "$ref_dir/../../../bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_xlslice_0_0/sim/zcu106_hdmi_platform_xlslice_0_0.v" \
    "$ref_dir/../../../bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_zero_48bit_0/sim/zcu106_hdmi_platform_zero_48bit_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_pkg_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/0513/hdl/lib_pkg_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work interrupt_control_v3_1_4 $vhdlan_opts \
    "$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/8e66/hdl/interrupt_control_v3_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_iic_v2_0_19 $vhdlan_opts \
    "$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/6964/hdl/axi_iic_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_hdmi_ctrl_iic_0/sim/zcu106_hdmi_platform_hdmi_ctrl_iic_0.vhd" \
    "$ref_dir/../../../bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_proc_sys_reset_0_0/sim/zcu106_hdmi_platform_proc_sys_reset_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work axi_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/4903" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/472d/hdl/src/verilog" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/ad7b/hdl" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/0ab1/hdl" +incdir+"D:/tools/xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/4903" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/472d/hdl/src/verilog" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/ad7b/hdl" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/0ab1/hdl" +incdir+"D:/tools/xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/02c8/hdl/sc_util_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_protocol_checker_v2_0_2 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/4903" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/472d/hdl/src/verilog" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/ad7b/hdl" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/0ab1/hdl" +incdir+"D:/tools/xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/3755/hdl/axi_protocol_checker_v2_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_vip_v1_1_2 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/4903" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/472d/hdl/src/verilog" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/ad7b/hdl" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/0ab1/hdl" +incdir+"D:/tools/xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/725c/hdl/axi_vip_v1_1_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work zynq_ultra_ps_e_vip_v1_0_2 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/4903" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/472d/hdl/src/verilog" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/ad7b/hdl" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/0ab1/hdl" +incdir+"D:/tools/xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/ad7b/hdl/zynq_ultra_ps_e_vip_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/4903" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/472d/hdl/src/verilog" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/ad7b/hdl" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/0ab1/hdl" +incdir+"D:/tools/xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_zynq_ultra_ps_e_0_0/sim/zcu106_hdmi_platform_zynq_ultra_ps_e_0_0_vip_wrapper.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_register_slice_v2_1_16 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/4903" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/472d/hdl/src/verilog" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/ad7b/hdl" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/0ab1/hdl" +incdir+"D:/tools/xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/0cde/hdl/axi_register_slice_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_crossbar_v2_1_17 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/4903" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/472d/hdl/src/verilog" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/ad7b/hdl" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/0ab1/hdl" +incdir+"D:/tools/xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/d293/hdl/axi_crossbar_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/4903" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/472d/hdl/src/verilog" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/ad7b/hdl" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/0ab1/hdl" +incdir+"D:/tools/xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_xbar_4/sim/zcu106_hdmi_platform_xbar_4.v" \
    "$ref_dir/../../../bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_mixer_rst_0/sim/zcu106_hdmi_platform_mixer_rst_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work v_frmbuf_rd_v2_0_2 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/4903" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/472d/hdl/src/verilog" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/ad7b/hdl" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/0ab1/hdl" +incdir+"D:/tools/xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_v_frmbuf_rd_0_0/hdl/v_frmbuf_rd_v2_0_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/4903" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/472d/hdl/src/verilog" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/ad7b/hdl" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/0ab1/hdl" +incdir+"D:/tools/xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_v_frmbuf_rd_0_0/sim/zcu106_hdmi_platform_v_frmbuf_rd_0_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work v_hdmi_tx_v3_0_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/4903" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/472d/hdl/src/verilog" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/ad7b/hdl" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/0ab1/hdl" +incdir+"D:/tools/xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/791b/hdl/v_hdmi_tx_v3_0_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/4903" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/472d/hdl/src/verilog" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/ad7b/hdl" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/0ab1/hdl" +incdir+"D:/tools/xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_v_hdmi_tx_ss_0_0/bd_0/ip/ip_0/sim/bd_6ee1_v_hdmi_tx_0.sv" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_v_hdmi_tx_ss_0_0/bd_0/ip/ip_1/sim/bd_6ee1_v_tc_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work v_axi4s_vid_out_v4_0_9 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/4903" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/472d/hdl/src/verilog" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/ad7b/hdl" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/0ab1/hdl" +incdir+"D:/tools/xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/9a07/hdl/v_axi4s_vid_out_v4_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/4903" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/472d/hdl/src/verilog" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/ad7b/hdl" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/0ab1/hdl" +incdir+"D:/tools/xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_v_hdmi_tx_ss_0_0/bd_0/ip/ip_2/sim/bd_6ee1_v_axi4s_vid_out_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work util_vector_logic_v2_0_1 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/4903" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/472d/hdl/src/verilog" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/ad7b/hdl" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/0ab1/hdl" +incdir+"D:/tools/xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/2137/hdl/util_vector_logic_v2_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/4903" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/472d/hdl/src/verilog" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/ad7b/hdl" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/0ab1/hdl" +incdir+"D:/tools/xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_v_hdmi_tx_ss_0_0/bd_0/ip/ip_3/sim/bd_6ee1_util_vector_logic_0_0.v" \
    "$ref_dir/../../../bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_v_hdmi_tx_ss_0_0/bd_0/ip/ip_4/sim/bd_6ee1_axi_crossbar_0.v" \
    "$ref_dir/../../../bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_v_hdmi_tx_ss_0_0/bd_0/sim/bd_6ee1.v" \
    "$ref_dir/../../../bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_v_hdmi_tx_ss_0_0/sim/zcu106_hdmi_platform_v_hdmi_tx_ss_0_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work v_mix_v3_0_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/4903" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/472d/hdl/src/verilog" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/ad7b/hdl" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/0ab1/hdl" +incdir+"D:/tools/xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_v_mix_0_0/hdl/v_mix_v3_0_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/4903" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/472d/hdl/src/verilog" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/ad7b/hdl" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/0ab1/hdl" +incdir+"D:/tools/xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_v_mix_0_0/sim/zcu106_hdmi_platform_v_mix_0_0.v" \
    "$ref_dir/../../../bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_axi_data_fifo_0_0/sim/zcu106_hdmi_platform_axi_data_fifo_0_0.v" \
    "$ref_dir/../../../bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_v_frmbuf_wr_0_0/sim/zcu106_hdmi_platform_v_frmbuf_wr_0_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work v_hdmi_rx_v3_0_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/4903" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/472d/hdl/src/verilog" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/ad7b/hdl" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/0ab1/hdl" +incdir+"D:/tools/xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/f532/hdl/v_hdmi_rx_v3_0_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/4903" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/472d/hdl/src/verilog" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/ad7b/hdl" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/0ab1/hdl" +incdir+"D:/tools/xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_v_hdmi_rx_ss_0_0/bd_0/ip/ip_0/sim/bd_ceca_v_hdmi_rx_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/4903" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/472d/hdl/src/verilog" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/ad7b/hdl" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/0ab1/hdl" +incdir+"D:/tools/xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_v_hdmi_rx_ss_0_0/bd_0/ip/ip_1/sim/bd_ceca_v_vid_in_axi4s_0.v" \
    "$ref_dir/../../../bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_v_hdmi_rx_ss_0_0/bd_0/ip/ip_2/sim/bd_ceca_inverter_1_0.v" \
    "$ref_dir/../../../bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_v_hdmi_rx_ss_0_0/bd_0/sim/bd_ceca.v" \
    "$ref_dir/../../../bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_v_hdmi_rx_ss_0_0/sim/zcu106_hdmi_platform_v_hdmi_rx_ss_0_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work v_vscaler_v1_0_10 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/4903" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/472d/hdl/src/verilog" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/ad7b/hdl" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/0ab1/hdl" +incdir+"D:/tools/xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/v_vscaler_v1_0_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/4903" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/472d/hdl/src/verilog" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/ad7b/hdl" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/0ab1/hdl" +incdir+"D:/tools/xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_v_proc_ss_0_0/bd_0/ip/ip_2/sim/bd_e648_vsc_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work v_hscaler_v1_0_10 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/4903" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/472d/hdl/src/verilog" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/ad7b/hdl" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/0ab1/hdl" +incdir+"D:/tools/xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_v_proc_ss_0_0/bd_0/ip/ip_3/hdl/v_hscaler_v1_0_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/4903" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/472d/hdl/src/verilog" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/ad7b/hdl" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/0ab1/hdl" +incdir+"D:/tools/xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_v_proc_ss_0_0/bd_0/ip/ip_3/sim/bd_e648_hsc_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axis_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/4903" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/472d/hdl/src/verilog" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/ad7b/hdl" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/0ab1/hdl" +incdir+"D:/tools/xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/0ab1/hdl/axis_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axis_register_slice_v1_1_16 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/4903" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/472d/hdl/src/verilog" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/ad7b/hdl" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/0ab1/hdl" +incdir+"D:/tools/xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/000e/hdl/axis_register_slice_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/4903" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/472d/hdl/src/verilog" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/ad7b/hdl" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/0ab1/hdl" +incdir+"D:/tools/xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_v_proc_ss_0_0/bd_0/ip/ip_4/hdl/tdata_bd_e648_input_size_set_0.v" \
    "$ref_dir/../../../bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_v_proc_ss_0_0/bd_0/ip/ip_4/hdl/tuser_bd_e648_input_size_set_0.v" \
    "$ref_dir/../../../bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_v_proc_ss_0_0/bd_0/ip/ip_4/hdl/tstrb_bd_e648_input_size_set_0.v" \
    "$ref_dir/../../../bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_v_proc_ss_0_0/bd_0/ip/ip_4/hdl/tkeep_bd_e648_input_size_set_0.v" \
    "$ref_dir/../../../bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_v_proc_ss_0_0/bd_0/ip/ip_4/hdl/tid_bd_e648_input_size_set_0.v" \
    "$ref_dir/../../../bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_v_proc_ss_0_0/bd_0/ip/ip_4/hdl/tdest_bd_e648_input_size_set_0.v" \
    "$ref_dir/../../../bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_v_proc_ss_0_0/bd_0/ip/ip_4/hdl/tlast_bd_e648_input_size_set_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axis_subset_converter_v1_1_16 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/4903" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/472d/hdl/src/verilog" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/ad7b/hdl" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/0ab1/hdl" +incdir+"D:/tools/xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/3e4d/hdl/axis_subset_converter_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/4903" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/472d/hdl/src/verilog" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/ad7b/hdl" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/0ab1/hdl" +incdir+"D:/tools/xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_v_proc_ss_0_0/bd_0/ip/ip_4/hdl/top_bd_e648_input_size_set_0.v" \
    "$ref_dir/../../../bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_v_proc_ss_0_0/bd_0/ip/ip_4/sim/bd_e648_input_size_set_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_v_proc_ss_0_0/bd_0/ip/ip_5/sim/bd_e648_rst_axis_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_gpio_v2_0_18 $vhdlan_opts \
    "$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/fbf9/hdl/axi_gpio_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_v_proc_ss_0_0/bd_0/ip/ip_6/sim/bd_e648_reset_sel_axis_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/4903" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/472d/hdl/src/verilog" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/ad7b/hdl" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/0ab1/hdl" +incdir+"D:/tools/xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_v_proc_ss_0_0/bd_0/ip/ip_7/sim/bd_e648_axis_register_slice_0_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axis_data_fifo_v1_1_17 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/4903" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/472d/hdl/src/verilog" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/ad7b/hdl" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/0ab1/hdl" +incdir+"D:/tools/xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/36f8/hdl/axis_data_fifo_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/4903" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/472d/hdl/src/verilog" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/ad7b/hdl" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/0ab1/hdl" +incdir+"D:/tools/xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_v_proc_ss_0_0/bd_0/ip/ip_8/sim/bd_e648_axis_fifo_0.v" \
    "$ref_dir/../../../bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_v_proc_ss_0_0/bd_0/ip/ip_9/sim/bd_e648_xlslice_0_0.v" \
    "$ref_dir/../../../bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_v_proc_ss_0_0/bd_0/ip/ip_10/sim/bd_e648_xlslice_1_0.v" \
    "$ref_dir/../../../bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_v_proc_ss_0_0/bd_0/ip/ip_1/sim/bd_e648_xbar_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_clock_converter_v2_1_15 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/4903" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/472d/hdl/src/verilog" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/ad7b/hdl" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/0ab1/hdl" +incdir+"D:/tools/xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/d371/hdl/axi_clock_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/4903" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/472d/hdl/src/verilog" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/ad7b/hdl" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/0ab1/hdl" +incdir+"D:/tools/xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_v_proc_ss_0_0/bd_0/ip/ip_13/sim/bd_e648_auto_cc_2.v" \
    "$ref_dir/../../../bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_v_proc_ss_0_0/bd_0/ip/ip_12/sim/bd_e648_auto_cc_1.v" \
    "$ref_dir/../../../bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_v_proc_ss_0_0/bd_0/ip/ip_11/sim/bd_e648_auto_cc_0.v" \
    "$ref_dir/../../../bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_v_proc_ss_0_0/bd_0/sim/bd_e648.v" \
    "$ref_dir/../../../bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_v_proc_ss_0_0/sim/zcu106_hdmi_platform_v_proc_ss_0_0.v" \
    "$ref_dir/../../../bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_xlslice_1_0/sim/zcu106_hdmi_platform_xlslice_1_0.v" \
    "$ref_dir/../../../bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_const_vcc_0/sim/zcu106_hdmi_platform_const_vcc_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_ibufds_gt_0/util_ds_buf.vhd" \
    "$ref_dir/../../../bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_ibufds_gt_0/sim/zcu106_hdmi_platform_ibufds_gt_0.vhd" \
    "$ref_dir/../../../bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_ibufds_gt_odiv2_0/sim/zcu106_hdmi_platform_ibufds_gt_odiv2_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/4903" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/472d/hdl/src/verilog" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/ad7b/hdl" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/0ab1/hdl" +incdir+"D:/tools/xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_rx_scaler_reset_0/sim/zcu106_hdmi_platform_rx_scaler_reset_0.v" \
    "$ref_dir/../../../bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_tx_frmbuf_rd_aresetn_1_0/sim/zcu106_hdmi_platform_tx_frmbuf_rd_aresetn_1_0.v" \
    "$ref_dir/../../../bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_xbar_3/sim/zcu106_hdmi_platform_xbar_3.v" \
    "$ref_dir/../../../bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_xbar_2/sim/zcu106_hdmi_platform_xbar_2.v" \
    "$ref_dir/../../../bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_xbar_1/sim/zcu106_hdmi_platform_xbar_1.v" \
    "$ref_dir/../../../bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_xbar_0/sim/zcu106_hdmi_platform_xbar_0.v" \
    "$ref_dir/../../../bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_auto_cc_5/sim/zcu106_hdmi_platform_auto_cc_5.v" \
    "$ref_dir/../../../bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_auto_cc_4/sim/zcu106_hdmi_platform_auto_cc_4.v" \
    "$ref_dir/../../../bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_auto_cc_3/sim/zcu106_hdmi_platform_auto_cc_3.v" \
    "$ref_dir/../../../bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_auto_cc_2/sim/zcu106_hdmi_platform_auto_cc_2.v" \
    "$ref_dir/../../../bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_auto_cc_1/sim/zcu106_hdmi_platform_auto_cc_1.v" \
    "$ref_dir/../../../bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_auto_cc_0/sim/zcu106_hdmi_platform_auto_cc_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_protocol_converter_v2_1_16 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/4903" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/472d/hdl/src/verilog" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/ad7b/hdl" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/0ab1/hdl" +incdir+"D:/tools/xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/1229/hdl/axi_protocol_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work blk_mem_gen_v8_4_1 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/4903" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/472d/hdl/src/verilog" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/ad7b/hdl" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/0ab1/hdl" +incdir+"D:/tools/xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/67d8/simulation/blk_mem_gen_v8_4.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_dwidth_converter_v2_1_16 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/4903" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/472d/hdl/src/verilog" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/ad7b/hdl" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/0ab1/hdl" +incdir+"D:/tools/xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/2c2b/hdl/axi_dwidth_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/4903" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/472d/hdl/src/verilog" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/ad7b/hdl" +incdir+"$ref_dir/../../../../v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ipshared/0ab1/hdl" +incdir+"D:/tools/xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_auto_ds_0/sim/zcu106_hdmi_platform_auto_ds_0.v" \
    "$ref_dir/../../../bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_auto_pc_0/sim/zcu106_hdmi_platform_auto_pc_0.v" \
    "$ref_dir/../../../bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_m00_regslice_2/sim/zcu106_hdmi_platform_m00_regslice_2.v" \
    "$ref_dir/../../../bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_s01_regslice_2/sim/zcu106_hdmi_platform_s01_regslice_2.v" \
    "$ref_dir/../../../bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_s00_regslice_3/sim/zcu106_hdmi_platform_s00_regslice_3.v" \
    "$ref_dir/../../../bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_s00_regslice_2/sim/zcu106_hdmi_platform_s00_regslice_2.v" \
    "$ref_dir/../../../bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_auto_us_0/sim/zcu106_hdmi_platform_auto_us_0.v" \
    "$ref_dir/../../../bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_auto_rs_w_0/sim/zcu106_hdmi_platform_auto_rs_w_0.v" \
    "$ref_dir/../../../bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_m00_regslice_1/sim/zcu106_hdmi_platform_m00_regslice_1.v" \
    "$ref_dir/../../../bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_s01_regslice_1/sim/zcu106_hdmi_platform_s01_regslice_1.v" \
    "$ref_dir/../../../bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_s00_regslice_1/sim/zcu106_hdmi_platform_s00_regslice_1.v" \
    "$ref_dir/../../../bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_m00_regslice_0/sim/zcu106_hdmi_platform_m00_regslice_0.v" \
    "$ref_dir/../../../bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_s01_regslice_0/sim/zcu106_hdmi_platform_s01_regslice_0.v" \
    "$ref_dir/../../../bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_s00_regslice_0/sim/zcu106_hdmi_platform_s00_regslice_0.v" \
    "$ref_dir/../../../bd/zcu106_hdmi_platform/sim/zcu106_hdmi_platform.v" \
  2>&1 | tee -a vlogan.log


  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    glbl.v \
  2>&1 | tee -a vlogan.log

}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.zcu106_hdmi_platform xil_defaultlib.glbl -o zcu106_hdmi_platform_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./zcu106_hdmi_platform_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./zcu106_hdmi_platform.sh -help\" for more information)\n"
        exit 1
      fi
      create_lib_mappings $2
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
      create_lib_mappings $2
  esac

  create_lib_dir

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Define design library mappings
create_lib_mappings()
{
  file="synopsys_sim.setup"
  if [[ -e $file ]]; then
    if [[ ($1 == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  lib_map_path=""
  if [[ ($1 != "") ]]; then
    lib_map_path="$1"
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="$lib:$sim_lib_dir/$lib"
    echo $mapping >> $file
  done

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi
}

# Create design library directory paths
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# Delete generated data from the previous run
reset_run()
{
  files_to_remove=(ucli.key zcu106_hdmi_platform_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log 64 AN.DB csrc zcu106_hdmi_platform_simv.daidir)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done

  create_lib_dir
}

# Check command line arguments
check_args()
{
  if [[ ($1 == 1 ) && ($2 != "-lib_map_path" && $2 != "-noclean_files" && $2 != "-reset_run" && $2 != "-help" && $2 != "-h") ]]; then
    echo -e "ERROR: Unknown option specified '$2' (type \"./zcu106_hdmi_platform.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($2 == "-help" || $2 == "-h") ]]; then
    usage
  fi
}

# Script usage
usage()
{
  msg="Usage: zcu106_hdmi_platform.sh [-help]\n\
Usage: zcu106_hdmi_platform.sh [-lib_map_path]\n\
Usage: zcu106_hdmi_platform.sh [-reset_run]\n\
Usage: zcu106_hdmi_platform.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

# Launch script
run $1 $2
