# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/xilinx_prj/xilinx_FrameBuffer/xtp_hdmi_ex/hw/v_hdmi_tx_ss/v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_v_hdmi_rx_ss_0_0/zcu106_hdmi_platform_v_hdmi_rx_ss_0_0.xci
# IP: The module: 'zcu106_hdmi_platform_v_hdmi_rx_ss_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: d:/xilinx_prj/xilinx_FrameBuffer/xtp_hdmi_ex/hw/v_hdmi_tx_ss/v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_v_hdmi_rx_ss_0_0/bd_0/bd_ceca.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_ceca || ORIG_REF_NAME==bd_ceca} -quiet] -quiet

# IP: d:/xilinx_prj/xilinx_FrameBuffer/xtp_hdmi_ex/hw/v_hdmi_tx_ss/v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_v_hdmi_rx_ss_0_0/bd_0/ip/ip_0/bd_ceca_v_hdmi_rx_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_ceca_v_hdmi_rx_0 || ORIG_REF_NAME==bd_ceca_v_hdmi_rx_0} -quiet] -quiet

# IP: d:/xilinx_prj/xilinx_FrameBuffer/xtp_hdmi_ex/hw/v_hdmi_tx_ss/v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_v_hdmi_rx_ss_0_0/bd_0/ip/ip_1/bd_ceca_v_vid_in_axi4s_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_ceca_v_vid_in_axi4s_0 || ORIG_REF_NAME==bd_ceca_v_vid_in_axi4s_0} -quiet] -quiet

# IP: d:/xilinx_prj/xilinx_FrameBuffer/xtp_hdmi_ex/hw/v_hdmi_tx_ss/v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_v_hdmi_rx_ss_0_0/bd_0/ip/ip_2/bd_ceca_inverter_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_ceca_inverter_1_0 || ORIG_REF_NAME==bd_ceca_inverter_1_0} -quiet] -quiet

# XDC: d:/xilinx_prj/xilinx_FrameBuffer/xtp_hdmi_ex/hw/v_hdmi_tx_ss/v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_v_hdmi_rx_ss_0_0/bd_0/bd_ceca_ooc.xdc

# XDC: d:/xilinx_prj/xilinx_FrameBuffer/xtp_hdmi_ex/hw/v_hdmi_tx_ss/v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_v_hdmi_rx_ss_0_0/zcu106_hdmi_platform_v_hdmi_rx_ss_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zcu106_hdmi_platform_v_hdmi_rx_ss_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: d:/xilinx_prj/xilinx_FrameBuffer/xtp_hdmi_ex/hw/v_hdmi_tx_ss/v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_v_hdmi_rx_ss_0_0/zcu106_hdmi_platform_v_hdmi_rx_ss_0_0.xci
# IP: The module: 'zcu106_hdmi_platform_v_hdmi_rx_ss_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: d:/xilinx_prj/xilinx_FrameBuffer/xtp_hdmi_ex/hw/v_hdmi_tx_ss/v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_v_hdmi_rx_ss_0_0/bd_0/bd_ceca.bd
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_ceca || ORIG_REF_NAME==bd_ceca} -quiet] -quiet

# IP: d:/xilinx_prj/xilinx_FrameBuffer/xtp_hdmi_ex/hw/v_hdmi_tx_ss/v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_v_hdmi_rx_ss_0_0/bd_0/ip/ip_0/bd_ceca_v_hdmi_rx_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_ceca_v_hdmi_rx_0 || ORIG_REF_NAME==bd_ceca_v_hdmi_rx_0} -quiet] -quiet

# IP: d:/xilinx_prj/xilinx_FrameBuffer/xtp_hdmi_ex/hw/v_hdmi_tx_ss/v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_v_hdmi_rx_ss_0_0/bd_0/ip/ip_1/bd_ceca_v_vid_in_axi4s_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_ceca_v_vid_in_axi4s_0 || ORIG_REF_NAME==bd_ceca_v_vid_in_axi4s_0} -quiet] -quiet

# IP: d:/xilinx_prj/xilinx_FrameBuffer/xtp_hdmi_ex/hw/v_hdmi_tx_ss/v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_v_hdmi_rx_ss_0_0/bd_0/ip/ip_2/bd_ceca_inverter_1_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_ceca_inverter_1_0 || ORIG_REF_NAME==bd_ceca_inverter_1_0} -quiet] -quiet

# XDC: d:/xilinx_prj/xilinx_FrameBuffer/xtp_hdmi_ex/hw/v_hdmi_tx_ss/v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_v_hdmi_rx_ss_0_0/bd_0/bd_ceca_ooc.xdc

# XDC: d:/xilinx_prj/xilinx_FrameBuffer/xtp_hdmi_ex/hw/v_hdmi_tx_ss/v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_v_hdmi_rx_ss_0_0/zcu106_hdmi_platform_v_hdmi_rx_ss_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zcu106_hdmi_platform_v_hdmi_rx_ss_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
