# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/xilinx_prj/xilinx_FrameBuffer/xtp_hdmi_ex/hw/v_hdmi_tx_ss/v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_v_hdmi_tx_ss_0_0/zcu106_hdmi_platform_v_hdmi_tx_ss_0_0.xci
# IP: The module: 'zcu106_hdmi_platform_v_hdmi_tx_ss_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: d:/xilinx_prj/xilinx_FrameBuffer/xtp_hdmi_ex/hw/v_hdmi_tx_ss/v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_v_hdmi_tx_ss_0_0/bd_0/bd_6ee1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_6ee1 || ORIG_REF_NAME==bd_6ee1} -quiet] -quiet

# IP: d:/xilinx_prj/xilinx_FrameBuffer/xtp_hdmi_ex/hw/v_hdmi_tx_ss/v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_v_hdmi_tx_ss_0_0/bd_0/ip/ip_0/bd_6ee1_v_hdmi_tx_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_6ee1_v_hdmi_tx_0 || ORIG_REF_NAME==bd_6ee1_v_hdmi_tx_0} -quiet] -quiet

# IP: d:/xilinx_prj/xilinx_FrameBuffer/xtp_hdmi_ex/hw/v_hdmi_tx_ss/v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_v_hdmi_tx_ss_0_0/bd_0/ip/ip_1/bd_6ee1_v_tc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_6ee1_v_tc_0 || ORIG_REF_NAME==bd_6ee1_v_tc_0} -quiet] -quiet

# IP: d:/xilinx_prj/xilinx_FrameBuffer/xtp_hdmi_ex/hw/v_hdmi_tx_ss/v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_v_hdmi_tx_ss_0_0/bd_0/ip/ip_2/bd_6ee1_v_axi4s_vid_out_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_6ee1_v_axi4s_vid_out_0 || ORIG_REF_NAME==bd_6ee1_v_axi4s_vid_out_0} -quiet] -quiet

# IP: d:/xilinx_prj/xilinx_FrameBuffer/xtp_hdmi_ex/hw/v_hdmi_tx_ss/v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_v_hdmi_tx_ss_0_0/bd_0/ip/ip_3/bd_6ee1_util_vector_logic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_6ee1_util_vector_logic_0_0 || ORIG_REF_NAME==bd_6ee1_util_vector_logic_0_0} -quiet] -quiet

# IP: d:/xilinx_prj/xilinx_FrameBuffer/xtp_hdmi_ex/hw/v_hdmi_tx_ss/v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_v_hdmi_tx_ss_0_0/bd_0/ip/ip_4/bd_6ee1_axi_crossbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_6ee1_axi_crossbar_0 || ORIG_REF_NAME==bd_6ee1_axi_crossbar_0} -quiet] -quiet

# XDC: d:/xilinx_prj/xilinx_FrameBuffer/xtp_hdmi_ex/hw/v_hdmi_tx_ss/v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_v_hdmi_tx_ss_0_0/bd_0/bd_6ee1_ooc.xdc

# XDC: d:/xilinx_prj/xilinx_FrameBuffer/xtp_hdmi_ex/hw/v_hdmi_tx_ss/v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_v_hdmi_tx_ss_0_0/zcu106_hdmi_platform_v_hdmi_tx_ss_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zcu106_hdmi_platform_v_hdmi_tx_ss_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: d:/xilinx_prj/xilinx_FrameBuffer/xtp_hdmi_ex/hw/v_hdmi_tx_ss/v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_v_hdmi_tx_ss_0_0/zcu106_hdmi_platform_v_hdmi_tx_ss_0_0.xci
# IP: The module: 'zcu106_hdmi_platform_v_hdmi_tx_ss_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: d:/xilinx_prj/xilinx_FrameBuffer/xtp_hdmi_ex/hw/v_hdmi_tx_ss/v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_v_hdmi_tx_ss_0_0/bd_0/bd_6ee1.bd
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_6ee1 || ORIG_REF_NAME==bd_6ee1} -quiet] -quiet

# IP: d:/xilinx_prj/xilinx_FrameBuffer/xtp_hdmi_ex/hw/v_hdmi_tx_ss/v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_v_hdmi_tx_ss_0_0/bd_0/ip/ip_0/bd_6ee1_v_hdmi_tx_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_6ee1_v_hdmi_tx_0 || ORIG_REF_NAME==bd_6ee1_v_hdmi_tx_0} -quiet] -quiet

# IP: d:/xilinx_prj/xilinx_FrameBuffer/xtp_hdmi_ex/hw/v_hdmi_tx_ss/v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_v_hdmi_tx_ss_0_0/bd_0/ip/ip_1/bd_6ee1_v_tc_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_6ee1_v_tc_0 || ORIG_REF_NAME==bd_6ee1_v_tc_0} -quiet] -quiet

# IP: d:/xilinx_prj/xilinx_FrameBuffer/xtp_hdmi_ex/hw/v_hdmi_tx_ss/v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_v_hdmi_tx_ss_0_0/bd_0/ip/ip_2/bd_6ee1_v_axi4s_vid_out_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_6ee1_v_axi4s_vid_out_0 || ORIG_REF_NAME==bd_6ee1_v_axi4s_vid_out_0} -quiet] -quiet

# IP: d:/xilinx_prj/xilinx_FrameBuffer/xtp_hdmi_ex/hw/v_hdmi_tx_ss/v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_v_hdmi_tx_ss_0_0/bd_0/ip/ip_3/bd_6ee1_util_vector_logic_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_6ee1_util_vector_logic_0_0 || ORIG_REF_NAME==bd_6ee1_util_vector_logic_0_0} -quiet] -quiet

# IP: d:/xilinx_prj/xilinx_FrameBuffer/xtp_hdmi_ex/hw/v_hdmi_tx_ss/v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_v_hdmi_tx_ss_0_0/bd_0/ip/ip_4/bd_6ee1_axi_crossbar_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_6ee1_axi_crossbar_0 || ORIG_REF_NAME==bd_6ee1_axi_crossbar_0} -quiet] -quiet

# XDC: d:/xilinx_prj/xilinx_FrameBuffer/xtp_hdmi_ex/hw/v_hdmi_tx_ss/v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_v_hdmi_tx_ss_0_0/bd_0/bd_6ee1_ooc.xdc

# XDC: d:/xilinx_prj/xilinx_FrameBuffer/xtp_hdmi_ex/hw/v_hdmi_tx_ss/v_hdmi_tx_ss.srcs/sources_1/bd/zcu106_hdmi_platform/ip/zcu106_hdmi_platform_v_hdmi_tx_ss_0_0/zcu106_hdmi_platform_v_hdmi_tx_ss_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zcu106_hdmi_platform_v_hdmi_tx_ss_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
