
set_false_path -from [get_cells v_mix_CTRL_s_axi_U/int_HwReg_width_reg[*]]
set_false_path -from [get_cells v_mix_CTRL_s_axi_U/int_HwReg_height_reg[*]]
set_false_path -from [get_cells v_mix_CTRL_s_axi_U/int_HwReg_video_format_reg[*]]
set_false_path -from [get_cells v_mix_CTRL_s_axi_U/int_HwReg_background_Y_R_reg[*]]
set_false_path -from [get_cells v_mix_CTRL_s_axi_U/int_HwReg_background_U_G_reg[*]]
set_false_path -from [get_cells v_mix_CTRL_s_axi_U/int_HwReg_background_V_B_reg[*]]
set_false_path -from [get_cells v_mix_CTRL_s_axi_U/int_HwReg_layerEnable_reg[*]]

set_false_path -from [get_cells v_mix_CTRL_s_axi_U/int_HwReg_layerAlpha_0_reg[*]]
set_false_path -from [get_cells v_mix_CTRL_s_axi_U/int_HwReg_layerStartX_0_reg[*]]
set_false_path -from [get_cells v_mix_CTRL_s_axi_U/int_HwReg_layerStartY_0_reg[*]]
set_false_path -from [get_cells v_mix_CTRL_s_axi_U/int_HwReg_layerWidth_0_reg[*]]
set_false_path -from [get_cells v_mix_CTRL_s_axi_U/int_HwReg_layerHeight_0_reg[*]]
set_false_path -from [get_cells v_mix_CTRL_s_axi_U/int_HwReg_layerStride_0_reg[*]]
set_false_path -from [get_cells v_mix_CTRL_s_axi_U/int_HwReg_layerScaleFactor_0_reg[*]]
set_false_path -from [get_cells v_mix_CTRL_s_axi_U/int_HwReg_layerVideoFormat_0_reg[*]]


set_false_path -from [get_cells v_mix_CTRL_s_axi_U/int_HwReg_layerAlpha_1_reg[*]]
set_false_path -from [get_cells v_mix_CTRL_s_axi_U/int_HwReg_layerStartX_1_reg[*]]
set_false_path -from [get_cells v_mix_CTRL_s_axi_U/int_HwReg_layerStartY_1_reg[*]]
set_false_path -from [get_cells v_mix_CTRL_s_axi_U/int_HwReg_layerWidth_1_reg[*]]
set_false_path -from [get_cells v_mix_CTRL_s_axi_U/int_HwReg_layerHeight_1_reg[*]]
set_false_path -from [get_cells v_mix_CTRL_s_axi_U/int_HwReg_layerStride_1_reg[*]]
set_false_path -from [get_cells v_mix_CTRL_s_axi_U/int_HwReg_layerScaleFactor_1_reg[*]]
set_false_path -from [get_cells v_mix_CTRL_s_axi_U/int_HwReg_layerVideoFormat_1_reg[*]]

set_false_path -from [get_cells v_mix_CTRL_s_axi_U/int_HwReg_layerAlpha_2_reg[*]]
set_false_path -from [get_cells v_mix_CTRL_s_axi_U/int_HwReg_layerStartX_2_reg[*]]
set_false_path -from [get_cells v_mix_CTRL_s_axi_U/int_HwReg_layerStartY_2_reg[*]]
set_false_path -from [get_cells v_mix_CTRL_s_axi_U/int_HwReg_layerWidth_2_reg[*]]
set_false_path -from [get_cells v_mix_CTRL_s_axi_U/int_HwReg_layerHeight_2_reg[*]]
set_false_path -from [get_cells v_mix_CTRL_s_axi_U/int_HwReg_layerStride_2_reg[*]]
set_false_path -from [get_cells v_mix_CTRL_s_axi_U/int_HwReg_layerScaleFactor_2_reg[*]]
set_false_path -from [get_cells v_mix_CTRL_s_axi_U/int_HwReg_layerVideoFormat_2_reg[*]]

set_false_path -from [get_cells v_mix_CTRL_s_axi_U/int_HwReg_layerAlpha_3_reg[*]]
set_false_path -from [get_cells v_mix_CTRL_s_axi_U/int_HwReg_layerStartX_3_reg[*]]
set_false_path -from [get_cells v_mix_CTRL_s_axi_U/int_HwReg_layerStartY_3_reg[*]]
set_false_path -from [get_cells v_mix_CTRL_s_axi_U/int_HwReg_layerWidth_3_reg[*]]
set_false_path -from [get_cells v_mix_CTRL_s_axi_U/int_HwReg_layerHeight_3_reg[*]]
set_false_path -from [get_cells v_mix_CTRL_s_axi_U/int_HwReg_layerStride_3_reg[*]]
set_false_path -from [get_cells v_mix_CTRL_s_axi_U/int_HwReg_layerScaleFactor_3_reg[*]]
set_false_path -from [get_cells v_mix_CTRL_s_axi_U/int_HwReg_layerVideoFormat_3_reg[*]]

set_false_path -from [get_cells v_mix_CTRL_s_axi_U/int_HwReg_layerAlpha_4_reg[*]]
set_false_path -from [get_cells v_mix_CTRL_s_axi_U/int_HwReg_layerStartX_4_reg[*]]
set_false_path -from [get_cells v_mix_CTRL_s_axi_U/int_HwReg_layerStartY_4_reg[*]]
set_false_path -from [get_cells v_mix_CTRL_s_axi_U/int_HwReg_layerWidth_4_reg[*]]
set_false_path -from [get_cells v_mix_CTRL_s_axi_U/int_HwReg_layerHeight_4_reg[*]]
set_false_path -from [get_cells v_mix_CTRL_s_axi_U/int_HwReg_layerStride_4_reg[*]]
set_false_path -from [get_cells v_mix_CTRL_s_axi_U/int_HwReg_layerScaleFactor_4_reg[*]]
set_false_path -from [get_cells v_mix_CTRL_s_axi_U/int_HwReg_layerVideoFormat_4_reg[*]]

set_false_path -from [get_cells v_mix_CTRL_s_axi_U/int_HwReg_layerAlpha_5_reg[*]]
set_false_path -from [get_cells v_mix_CTRL_s_axi_U/int_HwReg_layerStartX_5_reg[*]]
set_false_path -from [get_cells v_mix_CTRL_s_axi_U/int_HwReg_layerStartY_5_reg[*]]
set_false_path -from [get_cells v_mix_CTRL_s_axi_U/int_HwReg_layerWidth_5_reg[*]]
set_false_path -from [get_cells v_mix_CTRL_s_axi_U/int_HwReg_layerHeight_5_reg[*]]
set_false_path -from [get_cells v_mix_CTRL_s_axi_U/int_HwReg_layerStride_5_reg[*]]
set_false_path -from [get_cells v_mix_CTRL_s_axi_U/int_HwReg_layerScaleFactor_5_reg[*]]
set_false_path -from [get_cells v_mix_CTRL_s_axi_U/int_HwReg_layerVideoFormat_5_reg[*]]

set_false_path -from [get_cells v_mix_CTRL_s_axi_U/int_HwReg_layerAlpha_6_reg[*]]
set_false_path -from [get_cells v_mix_CTRL_s_axi_U/int_HwReg_layerStartX_6_reg[*]]
set_false_path -from [get_cells v_mix_CTRL_s_axi_U/int_HwReg_layerStartY_6_reg[*]]
set_false_path -from [get_cells v_mix_CTRL_s_axi_U/int_HwReg_layerWidth_6_reg[*]]
set_false_path -from [get_cells v_mix_CTRL_s_axi_U/int_HwReg_layerHeight_6_reg[*]]
set_false_path -from [get_cells v_mix_CTRL_s_axi_U/int_HwReg_layerStride_6_reg[*]]
set_false_path -from [get_cells v_mix_CTRL_s_axi_U/int_HwReg_layerScaleFactor_6_reg[*]]
set_false_path -from [get_cells v_mix_CTRL_s_axi_U/int_HwReg_layerVideoFormat_6_reg[*]]

set_false_path -from [get_cells v_mix_CTRL_s_axi_U/int_HwReg_layerAlpha_7_reg[*]]
set_false_path -from [get_cells v_mix_CTRL_s_axi_U/int_HwReg_layerStartX_7_reg[*]]
set_false_path -from [get_cells v_mix_CTRL_s_axi_U/int_HwReg_layerStartY_7_reg[*]]
set_false_path -from [get_cells v_mix_CTRL_s_axi_U/int_HwReg_layerWidth_7_reg[*]]
set_false_path -from [get_cells v_mix_CTRL_s_axi_U/int_HwReg_layerHeight_7_reg[*]]
set_false_path -from [get_cells v_mix_CTRL_s_axi_U/int_HwReg_layerStride_7_reg[*]]
set_false_path -from [get_cells v_mix_CTRL_s_axi_U/int_HwReg_layerScaleFactor_7_reg[*]]
set_false_path -from [get_cells v_mix_CTRL_s_axi_U/int_HwReg_layerVideoFormat_7_reg[*]]


